**Import Library**

In [7]:
import pandas as pd

**Load Dataset**

In [11]:
# load dataset
url_1 = "https://raw.githubusercontent.com/IzzahHuwaidah/Predicting-Stress-Levels-Using-Sleep-Pattern-Data/refs/heads/main/mental_health_dataset.csv"
url_2 = "https://raw.githubusercontent.com/IzzahHuwaidah/Predicting-Stress-Levels-Using-Sleep-Pattern-Data/refs/heads/main/Global_Lifespan_Determinant.csv"
data_1= pd.read_csv(url_1)
data_2 = pd.read_csv(url_2)

**Overview dataset**

In [12]:
# menampilkan 5 data pertama data 1
data_1.head()

,age,gender,employment_status,work_environment,mental_health_history,seeks_treatment,stress_level,sleep_hours,physical_activity_days,depression_score,anxiety_score,social_support_score,productivity_score,mental_health_risk
0,56,Male,Employed,On-site,Yes,Yes,6,6.2,3,28,17,54,59.7,High
1,46,Female,Student,On-site,No,Yes,10,9.0,4,30,11,85,54.9,High
2,32,Female,Employed,On-site,Yes,No,7,7.7,2,24,7,62,61.3,Medium
3,60,Non-binary,Self-employed,On-site,No,No,4,4.5,4,6,0,95,97.0,Low
4,25,Female,Self-employed,On-site,Yes,Yes,3,5.4,0,24,12,70,69.0,High

In [13]:
# menampilkan 5 data pertama dataset 2
data_2.head()

,Unnamed: 0,TOTAL_AGE,SEX,SMOKING_STATUS,PHYSICAL_ACTIVITY_HOURS_PER_DAY,SLEEP_HOURS,BMI,STRESS_LEVEL,PROFESSION,EDUCATION_LEVEL,DIET_CALORIES,DISEASES_SUFFERIN_FROM,COUNTRY,HEALTH_RISK_SCORE,LIFESTYLE_SCORE
0,0,66.0,Male,Never,4.0,6.1,29.9,0.32,Teacher,PhD,3125,3,Canada,19.2863,7.8509
1,1,73.0,Female,Never,2.3,6.8,25.3,0.43,Doctor,Master's Degree,3462,11,Indonesia,23.9758,6.7363
2,2,71.0,Female,Never,5.9,7.9,24.8,0.69,Police,PhD,2021,9,Indonesia,36.6935,9.2592
3,3,66.8,Female,Medium,5.4,5.0,24.2,0.49,Soldier,Bachelor's Degree,3992,8,Canada,26.5986,3.4177
4,4,60.0,Female,High,3.9,8.9,26.1,0.74,Engineer,Some College,2463,7,Bangladesh,39.1394,2.9095